# Main entrypoint of the workflow. 
# Please follow the best practices: 
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there. 

rule touch:
    output: "file.txt"
    conda: "envs/empty.yaml"
    log: "logs/touch.log"
    shell:
        "touch {output}"
